import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        
      <body className={inter.className}>
      <div className="h-10 items-center flex justify-center sticky top-0 left-0 bg-foreground w-full">
        <h1 className="text-muted flex items-center justify-center">BUKAR</h1>
      </div>
        {children}</body>
    </html>
  );
}
